### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by kubilaycaglayan** [nativescript-vue/nativescript-vue-devtools#22]
Hello, there!

Woke up with this random error.
If I remove the import (`import VueDevtools from "nativescript-vue-devtools";`) and remote the line(`Vue.use(VueDevtools);`) then I can use my application. Otherwise, this error is blocking.

Versions:
- "nativescript-vue": "~2.9.0",
- "nativescript-vue-devtools": "^1.5.1",

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: ReferenceError: document is not defined
System.err: File: (webpack-internal:///../app-backend-core/lib/hook.js:19:22)
System.err:
System.err: StackTrace:
System.err: injectToIframes(:19:23)
System.err: 	at installHook(:42:5)
System.err: 	at eval(:7:56)
System.err: 	at ./src/hook.js(file: app/webpack:/@nativescript/template-blank-vue-ts/node_modules/@vue/devtools/build/hook.js:39:0)
System.err: 	at __nested_webpack_require_79423__(file: app/webpack:/@nativescript/template-blank-vue-ts/node_modules/@vue/devtools/build/hook.js:63:0)
System.err: 	at (file: app/webpack:/@nativescript/template-blank-vue-ts/node_modules/@vue/devtools/build/hook.js:98:36)
System.err: 	at ./node_modules/@vue/devtools/build/hook.js(file: app/webpack:/@nativescript/template-blank-vue-ts/node_modules/@vue/devtools/build/hook.js:100:10)
System.err: 	at __webpack_require__(file: app/webpack:/@nativescript/template-blank-vue-ts/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@vue/devtools/index.js(file: app/webpack:/@nativescript/template-blank-vue-ts/node_modules/@vue/devtools/index.js:1:0)
System.err: 	at __webpack_require__(file: app/webpack:/@nativescript/template-blank-vue-ts/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/nativescript-vue-devtools/dist/index.js(file:///data/data/org.xxx/files/app/vendor.js:89883:71)
System.err: 	at __webpack_require__(file: app/webpack:/@nativescript/template-blank-vue-ts/webpack/bootstrap:19:0)
System.err: 	at ./app/app.ts(file:///data/data/org.xxx/files/app/bundle.js:15:83)
System.err: 	at __webpack_require__(file: app/webpack:/@nativescript/template-blank-vue-ts/webpack/bootstrap:19:0)
System.err: 	at __webpack_exec__(file:///data/data/org.xxx/files/app/bundle.js:21957:39)
System.err: 	at (file:///data/data/org.xxx/files/app/bundle.js:21958:143)
System.err: 	at __webpack_require__.X(file: app/webpack:/@nativescript/template-blank-vue-ts/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/org.xxx/files/app/bundle.js:21958:47)
System.err: 	at (file:///data/data/org.xxx/files/app/bundle.js:21963:3)
System.err: 	at require(:1:266)
System.err:
System.err:
System.err: ReferenceError: document is not defined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: ReferenceError: document is not defined
System.err: File: (webpack-internal:///../app-backend-core/lib/hook.js:19:22)
```

**Comment by peter-brennan** [comment]
what was the issue? i'm facing this atm.

**Comment by rigor789** [comment]
@peter-brennan what's the version of your `@vue/devtools` in package.json?
