### ISSUE TITLE
Following the docs I get "Reference Error: io is not defined"

### ISSUE THREAD

**Issue by eric-blue** [nativescript-vue/nativescript-vue-devtools#3]
Followed the [docs](https://nativescript-vue.org/en/docs/getting-started/vue-devtools/) exactly. 

Left with this:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

ReferenceError: io is not defined
File: "file:///data/data/org.nativescript.application/files/app/vendor.js, line: 30885, column: 15

StackTrace: 
	Frame: function:'../node_modules/nativescript-socket.io/socketio.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 30885, column: 16
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'io', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32065, column: 28
	Frame: function:'srcBackendJs', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 19983, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 59, column: 23
	Frame: function:'push.../node_modules/@vue/devtools/build/backend.js.../../node_modules/vue/dist/vue.runtime.esm.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 251, column: 10
	Frame: function:'../node_modules/@vue/devtools/build/backend.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 253, column: 3
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'connect', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 23001, column: 5
	Frame: function:'setupDevtools', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32058, column: 16
	Frame: function:'Vue.$start', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32076, column: 7
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4411, column: 4
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4416, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


ReferenceError: io is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'../node_modules/nativescript-socket.io/socketio.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 30885, column: 16
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'io', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32065, column: 28
	Frame: function:'srcBackendJs', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 19983, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 59, column: 23
	Frame: function:'push.../node_modules/@vue/devtools/build/backend.js.../../node_modules/vue/dist/vue.runtime.esm.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 251, column: 10
	Frame: function:'../node_modules/@vue/devtools/build/backend.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 253, column: 3
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'connect', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 23001, column: 5
	Frame: function:'setupDevtools', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32058, column: 16
	Frame: function:'Vue.$start', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32076, column: 7
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4411, column: 4
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4416, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


ReferenceError: io is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'../node_modules/nativescript-socket.io/socketio.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 30885, column: 16
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'io', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32065, column: 28
	Frame: function:'srcBackendJs', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 19983, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 59, column: 23
	Frame: function:'push.../node_modules/@vue/devtools/build/backend.js.../../node_modules/vue/dist/vue.runtime.esm.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 251, column: 10
	Frame: function:'../node_modules/@vue/devtools/build/backend.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 253, column: 3
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'connect', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 23001, column: 5
	Frame: function:'setupDevtools', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32058, column: 16
	Frame: function:'Vue.$start', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32076, column: 7
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4411, column: 4
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4416, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

ReferenceError: io is not defined
File: "file:///data/data/org.nativescript.application/files/app/vendor.js, line: 30885, column: 15

StackTrace: 
	Frame: function:'../node_modules/nativescript-socket.io/socketio.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 30885, column: 16
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'io', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32065, column: 28
	Frame: function:'srcBackendJs', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 19983, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 59, column: 23
	Frame: function:'push.../node_modules/@vue/devtools/build/backend.js.../../node_modules/vue/dist/vue.runtime.esm.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 251, column: 10
	Frame: function:'../node_modules/@vue/devtools/build/backend.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 253, column: 3
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'connect', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 23001, column: 5
	Frame: function:'setupDevtools', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32058, column: 16
	Frame: function:'Vue.$start', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32076, column: 7
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4411, column: 4
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4416, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


ReferenceError: io is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'../node_modules/nativescript-socket.io/socketio.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 30885, column: 16
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'io', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32065, column: 28
	Frame: function:'srcBackendJs', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 19983, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 59, column: 23
	Frame: function:'push.../node_modules/@vue/devtools/build/backend.js.../../node_modules/vue/dist/vue.runtime.esm.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 251, column: 10
	Frame: function:'../node_modules/@vue/devtools/build/backend.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 253, column: 3
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'connect', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 23001, column: 5
	Frame: function:'setupDevtools', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32058, column: 16
	Frame: function:'Vue.$start', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32076, column: 7
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4411, column: 4
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4416, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


ReferenceError: io is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'../node_modules/nativescript-socket.io/socketio.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 30885, column: 16
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'io', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32065, column: 28
	Frame: function:'srcBackendJs', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 19983, column: 18
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 59, column: 23
	Frame: function:'push.../node_modules/@vue/devtools/build/backend.js.../../node_modules/vue/dist/vue.runtime.esm.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 251, column: 10
	Frame: function:'../node_modules/@vue/devtools/build/backend.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 253, column: 3
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'connect', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 23001, column: 5
	Frame: function:'setupDevtools', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32058, column: 16
	Frame: function:'Vue.$start', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 32076, column: 7
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4411, column: 4
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 4416, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:553)
	at com.tns.Runtime.run(Runtime.java:545)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
	... 8 more
```

Android Emulator: Nexus5X (API 28)

**Comment by f3ltron** [comment]
same issue here

**Comment by peanut24** [comment]
Same here, any update on this?

**Comment by eric-blue** [comment]
Seems this repo is abandoned

**Comment by eric-blue** [comment]
awesome, go @rigor789 !

**Comment by rigor789** [comment]
There's a lot of work involved across all the repositories I maintain - so it takes time to get to some of these issues! 💯

**Comment by tanc** [comment]
I've updated to the latest version with the fix but I still see `ReferenceError: io is not defined` and there is no connection to the vue devtools instance (just see Waiting for connection...)

**Comment by rigor789** [comment]
@tanc please share a project, or at least a stack trace and `package.json`
